### ISSUE TITLE
No error message when Test::Expander should autodetect $CLASS but cannot find the .pm file in the @INC

### ISSUE THREAD

**Issue by knmiecc** [jsf116/Test-Expander#2]
When trying to use the expectedly autodetected symbol $CLASS in the following case, it quietly fails and does not report that `$CLASS` was not exported when running it verbosely.

In a testfile do.t in a test directory '/t/Foo/Bar/Baz' we want to access `$CLASS`. 
A corresponding module has been created in a directory 'lib/Foo/Bar/' under Baz.pm, that has the package line `package Foo::Bar::Baz`.
The lib/ directory was erroneously not included yet into `@INC` and thus Foo::Bar::Baz could not be found.

Instead of reporting that Foo::Bar::Baz was not found, Test::Expander quietly dropped `$CLASS` and all subsequent uses of it fail.

Please add a (verbose level) error message when $CLASS should be autodetected based on the test directory structure, but the corresponding directory could not be located or loaded.

**Comment by jsf116** [comment]
Starting from the version **2.4.0**, **Test::Expander** reports both exported and unexported read-only variables **$CLASS**, **$METHOD**, and **$METHOD_REF**.
Starting from the version **2.5.0** (currently the most recent one) **Test::Expander** supports customized colorization reporting exported and unexported read-only variables.
